### ISSUE TITLE
[Bug] Riru is crashing on Samsung Galaxy A41 after the UI Launches

### ISSUE THREAD

**Issue by hafometh88** [RikkaApps/Riru#302] opened 2021-11-10 07:24 UTC
### This is a bug of Riru itself

- [X] This is a bug of Riru, not a bug of a Riru module or something else

### Other modules are disabled

- [X] Except Riru itself, all other Magisk modules are disabled

### Zygisk are disabled

- [X] I know that Zygisk and Riru are not compatible and Zygisk has been disabled

### Riru version

26.1.3

### Android version

10

### Device

Samsung Galaxy A41

### Describe the bug

Steps to reproduce:

1. Install Riru with Magisk
2. Reboot the phone
3. Enter the passcode
4. Seconds after the UI loads the phone hard reboots (ADB disconnects as well)

I tried reflashing the phone twice with stock fw, but no luck

### Relevant logs

```shell
log is in attachment
```

**Comment by hafometh88** [comment] 2021-11-10 07:24
[log.txt](https://github.com/RikkaApps/Riru/files/7510649/log.txt)

Complete log in the timeframe of the phone being unlocked to itself crashing

**Comment by yujincheng08** [comment] 2021-11-10 07:35
Duplicate of #212

**Closed by yujincheng08** 2021-11-10 07:35 UTC
Labels: bug

**Comment by hafometh88** [comment] 2021-11-10 08:13
I highly doubt this is the case, because Riru works just fine on a similiar device from same time period that is Samsung Galaxy Tab 10 (2019). Also a thing I just encountered, there is a small chance the phone is actually stable after many reboots, but it of course goes again next reboot. So if you excuse me, I think the explanation you gave in #212 is either incorrect or not correct in relation to this particular device.

**Comment by yujincheng08** [comment] 2021-11-10 08:14
It is the case:
> Process com.samsung.android.knox.containercore (pid 3188) has died

**Comment by hafometh88** [comment] 2021-11-10 08:21
Can't I just disable knox ?

**Comment by yujincheng08** [comment] 2021-11-10 08:23
I doubt if it's enough. But at least you can have a try.

**Comment by hafometh88** [comment] 2021-11-10 08:32
yeah doesn't seem to make a difference
