### ISSUE TITLE
Riru videos not playing.

### ISSUE THREAD

**Issue by AgusBJ02** [RikkaApps/Riru#122] opened 2020-10-17 05:18 UTC
When i install riru core, i can't play vídeos. On Samsung G570M. ROM CAOS aosp android 10 (gsi ROM).

**Comment by RikkaW** [comment] 2020-10-17 07:09
Try to install Riru itself only (disable all other Riru modules) and check if the problem is gone.
If not, try the latest alpha (https://github.com/RikkaApps/Riru/releases/tag/v22.0-alpha03) which uses a totally different way.

**Comment by AgusBJ02** [comment] 2020-10-18 04:22
I tried installing the 21.x and the alpha 22.0 and it gives the same resulta. Only Riru Core is enabled.

**Comment by AgusBJ02** [comment] 2020-10-18 04:25
I'm using Magisk 20.4 phh a-only

**Comment by RikkaW** [comment] 2020-10-18 05:48
Need some more information.
1. Which videos cannot be played? Chrome? Netflix? or a simple video app that uses system API directly?
2. The content of `/system/etc/public.libraries.txt` with and without Riru v22

**Comment by AgusBJ02** [comment] 2020-10-18 16:04
every time I want to play the video, the app freezes, be it YouTube, gallery, etc.

File withouth Riru
See https://android.googlesource.com/platform/ndk/+/master/docs/PlatformApis.md
libandroid.so
libaaudio.so
libamidi.so
libbinder_ndk.so
libc.so
libcamera2ndk.so
libdl.so
libEGL.so
libGLESv1_CM.so
libGLESv2.so
libGLESv3.so
libicui18n.so
libicuuc.so
libjnigraphics.so
liblog.so
libmediandk.so
libm.so
libnativewindow.so
libneuralnetworks.so
libOpenMAXAL.so
libOpenSLES.so
libRS.so
libstdc++.so
libsync.so
libvulkan.so
libwebviewchromium_plat_support.so
libz.so

File with Riru
 See https://android.googlesource.com/platform/ndk/+/master/docs/PlatformApis.md
libandroid.so
libaaudio.so
libamidi.so
libbinder_ndk.so
libc.so
libcamera2ndk.so
libdl.so
libEGL.so
libGLESv1_CM.so
libGLESv2.so
libGLESv3.so
libicui18n.so
libicuuc.so
libjnigraphics.so
liblog.so
libmediandk.so
libm.so
libnativewindow.so
libneuralnetworks.so
libOpenMAXAL.so
libOpenSLES.so
libRS.so
libstdc++.so
libsync.so
libvulkan.so
libwebviewchromium_plat_support.so
libz.so
libriru.so

**Comment by RikkaW** [comment] 2020-10-24 06:00
`adb logcat > 1.txt` and reproduce the problem.

**Comment by RikkaW** [comment] 2020-10-31 03:41
Close this issue because there is no new reply.

😶 By the way, GSI means magic everywhere. <del>Just a guess, Magisk's magic mount may conflict with GSI.</del>

**Closed by RikkaW** 2020-10-31 03:41 UTC
